name: isl_translator
description: "Indian Sign Language Translator - Real-time ISL to Text/Speech"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  fl_chart: ^0.70.2
  flutter_tts: ^4.2.0
  camera: ^0.11.1
  percent_indicator: ^4.2.3
  tflite_flutter: ^0.11.0
  image: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ml/
